<%

require 'cgi'
require 'uri'

begin
  uri = URI.parse(ENV["REDIS_URL"])
rescue URI::InvalidURIError
  raise "Invalid REDIS_URL"
end

raise "No RACK_ENV or RAILS_ENV found" unless ENV["RAILS_ENV"] || ENV["RACK_ENV"]

def attribute(name, value)
  value ? "#{name}: \"#{value}\"" : ""
end

db = (uri.path || "").split("/")[1] || "0"

%>

defaults: &defaults
  <%= attribute "host",     uri.host %>
  <%= attribute "port",     uri.port %>
  <%= attribute "password", uri.password %>
  <%= attribute "db",       db %>

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
